### ISSUE TITLE
bug: binary file downloads

### ISSUE THREAD

**Issue by rdwz** [rdwz/get-vercel-source-code#9]
> [Get Deployment File Contents](https://vercel.com/docs/rest-api/endpoints#get-deployment-file-contents)
>
> `GET /v7/deployments/{id}/files/{fileId}`
>
> Allows to retrieve the content of a file by supplying the file identifier and the deployment unique identifier. The response body will contain a JSON response containing the contents of the file encoded as base64.

So data needed to be decoded before writing to file.
But now support of binary files is broken.

**Comment by rdwz** [comment]
Hi @MicroCBer,
I merged you change and worked fine until now as Vercel changed their API. Could you help me fix this again?

**Comment by rdwz** [comment]
fixed :)

**Comment by harbtech** [comment]
files are still saved as base64
